api/index.js
package.json
server.js
src/entry-server.js
src/util/comm.js
yarn.lock

in component.js, import the function like:
```
import { currDevice } from '../../util/comm'
console.log('current device is', currDevice(this.$store.state.os)) 
```

implment function currDevice to get the client device type

---

.drone.yml
.kube.yml
Dockerfile

Now this pipeline only build when merged.
Only deploy to k8s dev cluster

Integrate Drone pipeline

---

src/components/Farmhouse/Farmhouse.vue

farmhouse hamburger menu add standalone page link

---

src/components/Farmhouse/Faq_standalone.vue
src/components/Farmhouse/ImageComparison.vue
src/components/Farmhouse/Opinion_standalone.vue
src/components/Farmhouse/Violation.vue

調整 window resize 相關 function，移除 dispatchEvent 寫法

farmhouse, rewrite window resize function

---

src/App.vue
src/app.js
src/components/ForeignLabourIII/ForeignLabourIII.vue
src/router/index.js
src/store/actions.js
src/store/index.js
src/store/mutations.js

- add viewport state
- fix foreign labour iii event listener error
- move vue lazy-load setting to `app.js`

add viewport state and fix foreign labour iii event listener error

---

api/index.js
src/api/index.js
src/components/Dollclaw/Dollclaw.vue
src/components/Dollclaw/dcArticle.vue
src/components/RelatedReports.vue

- add dollclaw parallax effect
- adjust report api

add dollclaw parallax effect

---

src/components/Dollclaw/Dollclaw.vue
src/components/Dollclaw/dcArticle.vue
src/components/Dollclaw/dcFooter.vue

- add dollclaw ga event
- remove redundant code

add dollclaw ga event

---

src/components/ForeignLabourIV/ForeignLabourIV.vue
src/components/ForeignLabourLanding/ForeignLabourLanding.vue
src/components/Share.vue

- update `foreign labour landing`
- add `foreign labour iv` share, fb comment and ga event
- set share link to target blank

update foreign labour landing

---

package-lock.json
package.json
src/components/PresidentPromise/components/section/sectionResult/SectionResultSwiper.vue
src/components/PresidentPromise/util/service.js

replace superagent to axios

---

api/middle/election-board/index.js
src/components/ElectionBoard/DataBoard.vue
src/components/ElectionBoard/DataBoardsByCoordinate.vue
src/components/ElectionBoard/ElectionBoard.vue
src/components/ElectionBoard/ElectionBoardData.vue
src/components/ElectionBoard/ElectionBoardLanding.vue
src/components/ElectionBoard/ElectionBoardVerify.vue
src/components/ElectionBoard/FormSelectPosition.vue
src/components/ElectionBoard/VerifyInputCandidate.vue
src/store/modules/ElectionBoard/actions.js
src/store/modules/ElectionBoard/index.js
src/store/modules/ElectionBoard/mutations.js
src/store/modules/ElectionBoard/services.js

- add election board data part
- update verify part

add election board data part

---

src/components/AppHeader.vue

Also adjust `apiUrlDonate` in order to testing donate feature in `dev.readr.tw`.

send object_id and url while donate

---

src/components/ElectionBoard/DataBoards.vue
src/components/ElectionBoard/ElectionBoard.vue
src/components/ElectionBoard/ElectionBoardData.vue
src/components/ElectionBoard/ElectionBoardLanding.vue
src/components/ElectionBoard/ElectionBoardUpload.vue
src/components/ElectionBoard/ElectionBoardUploadForm.vue
src/components/ElectionBoard/ElectionBoardUploadMap.vue
src/components/ElectionBoard/ElectionBoardVerify.vue
src/components/ElectionBoard/FormSelectCandidate.vue
src/components/ElectionBoard/FormSelectDatetime.vue
src/components/ElectionBoard/FormSelectPosition.vue
src/components/ElectionBoard/VerifyInputCandidate.vue

This reverts commit 1a8b171d98bb9899a5fb46e2a62bf31bb2d17cb8.

Revert "modify layout of Home, Upload, Verify & Data (#562)"

---

.eslintrc
.gitignore
package.json
yarn.lock

- fix eslint setting
- update googleapis
- add package-lock.json to gitignore

fix eslint setting and update googleapis

---

src/components/Election2020/Election2020.vue
src/components/Election2020/components/Countdown.vue
src/components/Election2020/components/Header.vue
src/components/Election2020/components/LatestNews.vue
src/components/Election2020/templates/FirebaseCreateUpdate.vue
src/components/Election2020/templates/FirebaseRead.vue
src/components/SubscriptionWithLogoMsg.vue

- add `SubscriptionWithLogoMsg.vue`
- add `Header.vue`
- adjust style to use stylus variables
- adjust `Election2020.vue` style
- fix firebase sample components style

Election2020: add SubscriptionWithLogoMsg.vue and Header.vue

---

src/components/Election2020/Election2020.vue
src/components/Election2020/components/LightboxWrapper.vue

Add components for:
* LightboxWrapper
* lightbox 開啟時會自動鎖 html body scroll。
* props
* `showLightbox`: `Boolean`，顯示 lightbox 與否
* `type`: `String`，只接受 `normal` or `bingo`，預設為 `normal`，兩者差異在於 lightbox 的 style。
* slot
你可以利用 slot 放置任何自己想要的內容，如下
````
<LightboxWrapper
:showLightbox.sync="showLightbox"
>
<div>Your contents here</div>
</LightboxWrapper>
````

Election2020: add LightboxWrapper.vue component

---

src/components/Election2020/Election2020.vue
src/components/Election2020/components/Countdown.vue
src/components/Election2020/components/Header.vue
src/components/Election2020/components/LatestNews.vue
src/components/Election2020/components/PresidentCount.vue
src/components/Election2020/utility/common.js

- add `PresidentCount.vue`
- add utility function
- remove unnecessary stylus import

Election2020: add PresidentCount.vue and utility/common.js

---

src/components/Election2020/Election2020.vue
src/components/Election2020/components/PresidentCount.vue
src/components/Election2020/utility/common.js

- add PresidentCount default style
- fix formatRatio return type

Election2020: add PresidentCount style and fix formatRatio return

---

src/components/Election2020/Election2020.vue
src/components/Election2020/components/PresidentCount.vue
src/components/Election2020/components/PresidentCountChart.vue
src/store/modules/firebase-modules/realtimePresidents.js

- add `PresidentCountChart.vue`
- add startCounting getters 
- fix `PresidentCount.vue` style
- remove unnecessary code

Election2020: add president count chart

---

src/components/Election2020/Election2020.vue
src/components/Election2020/components/InfoDetailed.vue
src/constants/index.js

建了 `InfoDetailed.vue` 來呈現 tooltip 裡面形式的資料，如果覺得有更好的名字，也可以提出
然後加了 3 個範例在 `Election2020.vue` 可以參考，如果 props 吃的格式有出入的話，可以討論

Election2020: add InfoDetailed.vue and use fb sdk

---

src/components/Election2020/utility/mappings.js

ref: https://paper.dropbox.com/doc/--ArMdHkj92kejJtqmgy_R9aLcAg-FJjqVSXZlATzNPgu2Hr4k

Election2020: add mapPartyNameAbbr mapping

---

src/components/FactCheckDebate2020/FactCheckDebate2020.vue
src/components/FactCheckDebate2020/components/Item.vue
src/components/FactCheckDebate2020/index.css

og:image `fact-check-debate-2020/img/og_img.jpg` 需要上傳

FactCheckDebate2020: adjust styles

---

api/middle/googlesheet.js
src/components/Election2020/Election2020.vue

- remove mapping and tooltip example
- adjust latest news google sheet range 
- fix `api/middle/googlesheet.js` log format

Election2020: remove mapping and tooltip example

---

src/components/Election2020/components/bingo/BingoCell.vue
src/components/Election2020/components/bingo/BingoSection.vue
src/components/Election2020/components/bingo/BingoSelector.vue
src/components/Election2020/components/bingo/DistrictSelector.vue
src/components/Election2020/components/bingo/LagislatorSelector.vue
src/store/modules/Election2020/index.js
src/store/modules/Election2020/modules/bingo.js
src/store/modules/Election2020/modules/gcs.js

1. Add legislator selector for bingo with search functionality.
2. Integrate real data to the bingo legislator selector.

Bingo districted legislator selector

---

src/components/Election2020/components/InfoDetailed.vue
src/components/Election2020/components/legislator/LegislatorDistrict.vue

It seems there are missing `<thead>` and `<tbody>` wrapper, causing SSR issue.
so I wrap tableHeading with `<thead>` and tableData with `<tbody>`.

Election2020: fix missing tbody ssr issue

---

src/components/Election2020/Election2020.vue
src/components/Election2020/components/TheCredits.vue
src/components/Election2020/components/Tooltip.vue
src/components/Election2020/components/president/PresidentCountChart.vue
src/components/Election2020/utility/mappings.js

- add president winner change effect
- adjust Tooltip collision condition
- fix `PresidentCountChart.vue` tooltip  ssr warning
- remove unnecessary import

Election2020: add president winner change effect

---

src/components/Election2020/components/bingo/BingoCell.vue
src/components/Election2020/components/bingo/BingoFrame.vue
src/components/Election2020/components/bingo/BingoOthers.vue
src/components/Election2020/components/bingo/BingoSection.vue
src/components/Election2020/components/bingo/BingoStatus.vue

* add cursors icon to buttons
* fix layout in mobile

Election2020: Bug fixes and layout improvements

---

src/components/Election2020/components/bingo/BingoCell.vue
src/components/Election2020/components/bingo/BingoSection.vue

* Fix cursor
* Adjust font size for other's bingo frame detail in mobile

Election2020: Bug fixes

---

src/components/Election2020/components/InfoDetailed.vue
src/components/Election2020/components/president/PresidentCount.vue
src/components/Election2020/components/president/PresidentCountChart.vue
src/components/Election2020Embed/Election2020Embed.vue

- fix `InfoDetailed.vue` tks not show zero value
- fix `PresidentCount.vue` transition due to !important
- fix `PresidentCountChart.vue` and `Election2020Embed.vue` style

Election2020Embed: fix style and InfoDetailed tks issue

---

src/components/Election2020/components/bingo/BingoCell.vue
src/components/Election2020/components/bingo/BingoOthers.vue
src/components/Election2020/components/bingo/DistrictSelector.vue
src/store/modules/Election2020/modules/gcs.js

* Add other's bingo result selection buttons for mobile
* fix the name of aboriginal lagislator candidates
* Add zone detail info in the selector of regional lagistaltor candidates

Election2020: Layout optimize and Add info

---

src/components/Election2020/components/bingo/BingoMomentum.vue
src/components/Election2020/components/bingo/BingoMomentumCell.vue
src/components/Election2020/components/bingo/BingoSection.vue

* Remove the region description in bingo momentum section
* Try to fix bug that random selection buttom not removed when starting matching bingo

Election2020: Remove elements and try to fix bug

---

src/components/Election2020/components/bingo/BingoSelector.vue
src/components/Election2020/components/bingo/DistrictSelector.vue
src/components/Election2020/components/bingo/LagislatorSelector.vue
src/store/modules/Election2020/modules/bingo.js

* clear search query after the selector closed
* Add information in legislator selector: the selected name

 Election2020

---

src/components/Election2020/components/bingo/BingoFrame.vue
src/components/Election2020/components/bingo/BingoOthers.vue
src/components/Election2020/components/bingo/BingoStatus.vue
src/store/modules/Election2020/modules/bingo.js

* Fix a possibly infinite loop
* Clear the bingo timer

Election2020

---

api/middle/googlesheet.js
package.json
src/components/BackToFormosa/components/ReportPageContent.vue
src/components/MaskMap/MaskMap.vue
src/components/MaskMap/components/CommonInfo.vue
src/components/MaskMap/components/PharmacyInfo.vue
src/components/MaskMap/components/RelatedPosts.vue

以下 commit 已存在 master
- feat(MaskMap): 新增「相關文章」頁
- fix(BackToFormosa): fix <source> type attribute mistake

feat: add cors to googlesheet api

---

src/components/PoliticalContribution/components/charts/ParallelOrdinalPartyDonatesFrom.vue
src/components/PoliticalContribution/components/sections/sectionContent/SectionContentCredits.vue
src/components/PoliticalContribution/components/sections/sectionContent/SectionContentExplore/SectionContentExploreLightboxInfoDonatesFrom.vue

第十屆政治獻金 - 修正
